apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gcp-ingress
  namespace: demo
  annotations:
    # Reference the traffic policy
    k8s.ngrok.com/traffic-policy: hello-policy
spec:
  ingressClassName: ngrok
  rules:
  - host: ingress-demo.ngrok.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gcp
            port:
              number: 80
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  name: hello-policy
  namespace: demo
spec:
  policy:
    on_http_request:
      - actions:
          - type: restrict-ips
            config:
              enforce: true
              ip_policies:
                - ipp_30ZK1RXgctwBaDB3sgiIBkYqPb9
