apiVersion: v1
kind: Service
metadata:
  name: hello-gcp-2
  namespace: demo
spec:
  selector:
    app: hello-gcp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gcp-ingress
  namespace: demo
  annotations:
    k8s.ngrok.com/pooling-enabled: "true"
spec:
  ingressClassName: ngrok
  rules:
  - host: ingress-demo.ngrok.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gcp
            port:
              number: 80
---
# Second Ingress in the same pool for HA
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gcp-ingress-2
  namespace: demo
  annotations:
    k8s.ngrok.com/pooling-enabled: "true"
spec:
  ingressClassName: ngrok
  rules:
  - host: ingress-demo.ngrok.app  # Same host = shared pool
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gcp-2
            port:
              number: 80
