apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gcp-ingress
  namespace: demo
  annotations:
    # Reference the traffic policy
    ngrok.com/traffic-policy: hello-policy
spec:
  ingressClassName: ngrok
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gcp
            port:
              number: 80
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  name: hello-policy
  namespace: demo
spec:
  policy:
    on_http_response:
      - actions:
          - type: add-headers
            config:
              headers:
                x-demo-source: "ngrok-ingress"
                x-powered-by: "ngrok"
