apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gcp-ingress
  namespace: demo
spec:
  ingressClassName: ngrok
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gcp
            port:
              number: 80
